### ISSUE TITLE
TODO: research and fix resources_rc.py files in plugin repos

### ISSUE THREAD

**Issue by AndreasAtakan** [NapkinGIS/NapkinGIS-QGIS-plugin#1]
resources_rc.py files are somehow linked to the resources.qrc files governing the assets of the QGIS plugin. This needs to be updated with the new Napkin logos.

**Comment by AndreasAtakan** [comment]
Fixed and implemented

**Comment by Gustry** [comment]
FYI, I would simply remove the use of resource file.
It works well, no need to compile a file and to maintain it.

**Comment by Gustry** [comment]
Ah ok, I was going to approve your plugin, I miss it was already done
